services:
  postgres:
    image: postgres:17
    container_name: postgres-prod

    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - ./postgres-data:/var/lib/postgresql/data

    networks:
      - infra

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq-prod

    restart: unless-stopped

    env_file:
      - .env

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASSWORD: ${RABBITMQ_DEFAULT_PASSWORD}

    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"

    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq

    networks:
      - infra

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx

  #   restart: unless-stopped

  #   depends_on:
  #     - "80:80"
  #     - "443:443"

  #   network:
  #     - infra

  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/conf.d:/etc/nginx/conf.d:ro
  #     - ./ssl:/etc/ngin

  mysql:
    image: mysql:8.0
    container_name: mysql-prod

    restart: unless-stopped

    env_file:
      - .env

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - ./mysql-data:/var/lib/mysql

    networks:
      - infra

  kestra:
      build:
        context: ./kestra
        dockerfile: Dockerfile
      container_name: kestra
      restart: unless-stopped

      ports:
        - "8081:8080"

      user: root

      environment:
        SECRET_KESTRA_EXTERNAL_API_KEY: ${KESTRA_EXTERNAL_API_KEY}

        KESTRA_CONFIGURATION: |
          micronaut:
            io:
              watch:
                enabled: true
                paths:
                  - /flows

      volumes:
        - ./kestra/flows:/flows
        - ./kestra/storage:/app/storage
        - ./kestra/data:/app/data
        - /var/run/docker.sock:/var/run/docker.sock
        - /tmp:/tmp

      command: server local

      networks:
        - infra

  redis:
    image: redis:7-alpine
    container_name: infisical-redis
    restart: unless-stopped

    volumes:
      - ./redis-data:/data

    networks:
      - infra

  infisical:
    image: infisical/infisical:latest
    container_name: infisical-backend
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

    env_file:
      - .env

    environment:
      NODE_ENV: production

      # Infisical database
      DB_CONNECTION_URI: ${INFISICAL_DB_CONNECTION_URI}

      # Redis
      REDIS_URL: redis://redis:6379

    ports:
      - "7070:8080"

    networks:
      - infra

networks:
  infra:
    name: infra
    driver: bridge
